ALTER TYPE deal_status ADD VALUE IF NOT EXISTS 'REFUND_PENDING';
ALTER TYPE deal_status ADD VALUE IF NOT EXISTS 'DELIVERY_REJECTED';
ALTER TYPE deal_status ADD VALUE IF NOT EXISTS 'REVIEW_REQUIRED';
ALTER TYPE reputation_outcome ADD VALUE IF NOT EXISTS 'seller_breached_delivery';
