import { Profile, Listing, Deal, BuyerRequest } from '../types';
import { DbOffer, DbNegotiationMessage, DbDeal } from '../db/types';

export const demoProfiles: Record<string, Profile> = {
  'seller-probolinggo-cabai': {
    id: 'seller-probolinggo-cabai',
    displayName: 'Probolinggo Farmer Group',
    roleLabel: 'Aggregator & Farmer Group',
    location: 'Probolinggo, East Java',
    userType: 'seller',
    sellerScore: 92,
    buyerScore: 0,
    sellerCompletedCount: 15,
    buyerCompletedCount: 0,
    verifiedVolumeIdr: 450000000,
    proofVisibility: 'public',
    payoutRailPreference: 'wallet',
    payoutWalletLabel: 'Farmer treasury wallet',
    payoutWalletAddress: 'GCWQG2J4WLQG4ZB5PXJ4G3FQ4FQ3B6Q6L6M2Y7K4L5N2R6H4M1Q7S4AA',
    payoutBankName: 'Bank settlement rail',
    payoutBankAccountMasked: 'Not live in MVP',
  },
  'buyer-surabaya-restaurant': {
    id: 'buyer-surabaya-restaurant',
    displayName: 'Surabaya Spice Co.',
    roleLabel: 'Wholesale Buyer',
    location: 'Surabaya, East Java',
    userType: 'buyer',
    sellerScore: 0,
    buyerScore: 98,
    sellerCompletedCount: 0,
    buyerCompletedCount: 42,
    verifiedVolumeIdr: 1200000000,
    proofVisibility: 'public',
    payoutRailPreference: 'wallet',
    payoutWalletLabel: 'Procurement treasury wallet',
    payoutWalletAddress: 'GBL7R3X4YTF7Q7M6M2J3QK7A4ZJ5V8L2P6N4R9T2C7Y5M3W6K8A1B2CD',
    payoutBankName: 'Bank settlement rail',
    payoutBankAccountMasked: 'Not live in MVP',
  },
  'seller-sumatra-coffee': {
    id: 'seller-sumatra-coffee',
    displayName: 'Gayo Highland Cooperative',
    roleLabel: 'Cooperative',
    location: 'Aceh Tengah, Sumatra',
    userType: 'seller',
    sellerScore: 95,
    buyerScore: 0,
    sellerCompletedCount: 30,
    buyerCompletedCount: 0,
    verifiedVolumeIdr: 1500000000,
    proofVisibility: 'public',
    payoutRailPreference: 'wallet',
    payoutWalletLabel: 'Cooperative treasury wallet',
    payoutWalletAddress: 'GCF4Y2W8L9M1Q3S5T7V2X4Z6A8C1E3G5J7L9N2P4R6T8V1X3Z5B7D9EF',
    payoutBankName: 'Bank settlement rail',
    payoutBankAccountMasked: 'Not live in MVP',
  },
  'buyer-jakarta-factory': {
    id: 'buyer-jakarta-factory',
    displayName: 'Java Foods Manufacturing',
    roleLabel: 'Food Factory',
    location: 'Jakarta',
    userType: 'buyer',
    sellerScore: 0,
    buyerScore: 88,
    sellerCompletedCount: 0,
    buyerCompletedCount: 110,
    verifiedVolumeIdr: 5800000000,
    proofVisibility: 'private',
    payoutRailPreference: 'wallet',
    payoutWalletLabel: 'Factory settlement wallet',
    payoutWalletAddress: 'GDQ5S7W9Y2A4C6E8G1J3L5N7P9R2T4V6X8Z1B3D5F7H9K2M4Q6S8U1VW',
    payoutBankName: 'Bank settlement rail',
    payoutBankAccountMasked: 'Not live in MVP',
  }
};

export const demoListings: Listing[] = [
  {
    id: 'listing-cabai-001',
    sellerId: 'seller-probolinggo-cabai',
    commodity: "Red Chili (Bird's Eye Chili)",
    variety: "Bird's Eye Chili Grade A",
    status: 'ready_stock',
    location: 'Probolinggo',
    estimatedVolumeKg: 700,
    pricePerKgIdr: 28500,
    estimatedValueIdr: 19950000,
    description: 'Fresh harvest from Probolinggo group. Sorted and ready for pickup or delivery.',
  },
  {
    id: 'listing-coffee-001',
    sellerId: 'seller-sumatra-coffee',
    commodity: 'Arabica Green Beans',
    variety: 'Gayo Semi-Washed',
    status: 'pre_harvest',
    location: 'Aceh Tengah',
    estimatedVolumeKg: 2000,
    pricePerKgIdr: 95000,
    estimatedValueIdr: 190000000,
    harvestDate: '2026-07-15',
    description: 'Upcoming harvest. Strictly high grown, semi-washed preparation. Moisture <12%.',
  },
  {
    id: 'listing-rice-001',
    sellerId: 'seller-probolinggo-cabai',
    commodity: 'White Rice (Premium Milling)',
    variety: 'IR64 Premium',
    status: 'ready_stock',
    location: 'Pasuruan',
    estimatedVolumeKg: 5000,
    pricePerKgIdr: 13800,
    estimatedValueIdr: 69000000,
    description: 'Warehouse-ready premium white rice prepared for distributor or factory pickup.',
  },
];

export const demoBuyerRequests: BuyerRequest[] = [
  {
    id: 'req-spice-001',
    buyerId: 'buyer-surabaya-restaurant',
    commodity: "Red Chili (Bird's Eye Chili)",
    variety: "Bird's Eye Chili Grade A",
    status: 'open',
    deliveryLocation: 'Surabaya',
    requiredVolumeKg: 500,
    targetPricePerKgIdr: 28000,
    estimatedTotalIdr: 14000000,
    requiredDate: '2026-06-20',
    description: 'Looking for reliable supplier of grade A red chilies for continuous restaurant supply.',
  },
  {
    id: 'req-rice-001',
    buyerId: 'buyer-jakarta-factory',
    commodity: 'White Rice (Medium Grade)',
    variety: 'IR64 Medium',
    status: 'open',
    deliveryLocation: 'Jakarta',
    requiredVolumeKg: 10000,
    targetPricePerKgIdr: 12000,
    estimatedTotalIdr: 120000000,
    requiredDate: '2026-07-01',
    description: 'Bulk medium rice needed for factory processing. Must meet standard moisture requirements.',
  }
];

export const demoDeals: Record<string, Deal> = {
  'demo-cabai-001': {
    id: 'demo-cabai-001',
    listingId: 'listing-cabai-001',
    buyerId: 'buyer-surabaya-restaurant',
    sellerId: 'seller-probolinggo-cabai',
    commodity: "Red Chili (Bird's Eye Chili)",
    volumeKg: 700,
    principalIdr: 19950000,
    buyerBondIdr: 997500,
    sellerBondIdr: 997500,
    buyerFeeIdr: 99750,
    sellerFeeIdr: 99750,
    buyerTotalIdr: 21047250,
    sellerTotalIdr: 1097250,
    status: 'WAITING_DEPOSITS',
    stellarMode: 'not_configured',
    rail_version: 'managed_custody_testnet',
  },
};

export const demoOffers: Record<string, DbOffer> = {
  'offer-demo-cabai-001': {
    id: 'offer-demo-cabai-001',
    listing_id: 'listing-cabai-001',
    buyer_request_id: null,
    buyer_id: 'buyer-surabaya-restaurant',
    seller_id: 'seller-probolinggo-cabai',
    initiated_by_id: 'buyer-surabaya-restaurant',
    commodity: "Red Chili (Bird's Eye Chili)",
    volume_kg: 700,
    price_per_kg_idr: 28500,
    principal_idr: 19950000,
    terms_note: 'Same-week shipment, proof visible inside the protected room, and buyer pickup coordination after escrow lock.',
    status: 'active_escrow',
    latest_message_preview: 'We can prepare the lot as soon as both deposits clear in the active room.',
    terms_submitted_at: '2026-06-17T08:45:00.000Z',
    terms_accepted_at: '2026-06-17T09:06:00.000Z',
    terms_accepted_by_id: 'seller-probolinggo-cabai',
    buyer_open_room_at: '2026-06-17T09:10:00.000Z',
    seller_open_room_at: '2026-06-17T09:18:00.000Z',
    active_deal_id: 'demo-cabai-001',
    created_at: '2026-06-17T08:45:00.000Z',
    updated_at: '2026-06-17T09:18:00.000Z',
  }
};

export const demoOfferMessages: Record<string, DbNegotiationMessage[]> = {
  'offer-demo-cabai-001': [
    {
      id: 'offer-demo-cabai-001-msg-1',
      offer_id: 'offer-demo-cabai-001',
      author_id: 'buyer-surabaya-restaurant',
      body: 'We need 700 kg this week and want proof visibility inside the room.',
      created_at: '2026-06-17T08:45:00.000Z',
    },
    {
      id: 'offer-demo-cabai-001-msg-2',
      offer_id: 'offer-demo-cabai-001',
      author_id: 'seller-probolinggo-cabai',
      body: 'We can prepare the lot and upload shipment evidence after both deposits clear.',
      created_at: '2026-06-17T08:53:00.000Z',
    },
    {
      id: 'offer-demo-cabai-001-msg-3',
      offer_id: 'offer-demo-cabai-001',
      author_id: 'buyer-surabaya-restaurant',
      body: 'Understood. I am ready to open the Deal Room once you confirm the same terms.',
      created_at: '2026-06-17T09:02:00.000Z',
    }
  ]
};

export const demoDbDeals: Record<string, DbDeal> = {
  'demo-cabai-001': {
    id: 'demo-cabai-001',
    listing_id: 'listing-cabai-001',
    buyer_request_id: null,
    buyer_id: 'buyer-surabaya-restaurant',
    seller_id: 'seller-probolinggo-cabai',
    commodity: "Red Chili (Bird's Eye Chili)",
    volume_kg: 700,
    principal_idr: 19950000,
    buyer_bond_idr: 997500,
    seller_bond_idr: 997500,
    buyer_fee_idr: 99750,
    seller_fee_idr: 99750,
    buyer_total_idr: 21047250,
    seller_total_idr: 1097250,
    status: 'WAITING_DEPOSITS',
    stellar_escrow_id: null,
    stellar_mode: 'mock_only',
    stellar_contract_id: null,
    latest_stellar_tx_hash: null,
    stellar_sync_status: 'idle',
    proof_hash: null,
    terms: {
      offer_id: 'offer-demo-cabai-001'
    },
    created_at: '2026-06-17T09:18:00.000Z',
    updated_at: '2026-06-17T09:18:00.000Z',
  }
};
